---
title: "INDEPTH_Tonsil_Analysis"
author: "YYY"
output: html_document
---

Load packages
```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggcorrplot)
library(circlize)
library(GSVA)
library(Seurat)
library(enrichR)
```

Import data
```{r}
# Import data
L24_counts = read.csv(".../CPM-nNCG_3000-k_5_PostCorrectExp_L24.csv") %>%
  column_to_rownames(var = "X") %>% t() %>% as.data.frame() %>%
  rownames_to_column(var = "Region") %>% separate(Region, sep = "\\Q...\\E", into = c("Tissue", "Region", "CellType"))

L25_counts = read.csv(".../CPM-nNCG_2500-k_5_PostCorrectExp_L25.csv") %>%
  column_to_rownames(var = "X") %>% t() %>% as.data.frame() %>%
  rownames_to_column(var = "Region") %>% separate(Region, sep = "\\Q...\\E", into = c("Tissue", "Region", "CellType"))

Merged_counts = rbind(L24_counts, L25_counts)

head(L24_counts)
head(L25_counts)
head(Merged_counts)
```



Supp Fig 2E data
```{r}
# Import non-corrected data
L24_counts_uncorrected = read.csv(".../L24_norm.csv") %>% dplyr::filter(Region != "Control")
L25_counts_uncorrected = read.csv(".../L25_norm.csv") %>% dplyr::filter(Region != "Control")

Merged_counts_uncorrected = rbind(L24_counts_uncorrected, L25_counts_uncorrected)

head(Merged_counts_uncorrected)
```

Supp Fig 2E
```{r}
Merged_counts_uncorrected_bulk_celltype = Merged_counts_uncorrected %>%
  mutate(across(where(is.numeric), ~ 2^.)) %>%
  group_by(Tissue, CellType) %>%
  summarize(across(where(is.numeric), sum), .groups = "drop") %>%
  mutate(across(where(is.numeric), ~log2(.))) %>%
  pivot_longer(cols = -c(Tissue, CellType), 
               names_to = "Gene", 
               values_to = "Expression") %>%
  pivot_wider(names_from = Tissue, values_from = Expression)

#jpeg('.../SuppFig2E.jpg')
Merged_counts_uncorrected_bulk_celltype %>%
  ggplot(aes(x = `20240312_Tonsil_L24_ReScan2`,
             y = `20240312_Tonsil_L25`)) +
  geom_point(size = 0.5,
             alpha = 0.2) +
  geom_smooth(method = lm,
              se = TRUE) +
  #stat_cor(method = "pearson") +
  facet_wrap(~CellType) +
  theme_bw() +
  theme(panel.grid = element_blank())
#dev.off()
```

Supp Fig 2F
```{r}
# Total RNA
Tonsil_data_celltype = Merged_counts_uncorrected %>%
  mutate(across(where(is.numeric), ~2^.)) %>% # undo log2 first before summing values
  group_by(Tissue, Region, CellType) %>%
  summarize(across(where(is.numeric), sum), .groups = "drop") %>%
  mutate(Total_Sum = rowSums(across(where(is.numeric)))) %>%
  dplyr::select(Tissue, Region, CellType, Total_Sum) %>%
  mutate(across(where(is.numeric), ~log2(.))) # redo log2

#pdf('.../SuppFig2F.pdf')
ggplot(Tonsil_data_celltype,
       aes(x = Tissue,
           y = Total_Sum,
           fill = Tissue)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.25) +
  geom_point(size = 1) +
  geom_line(aes(group = Region),
            linewidth = 0.1) +
  labs(x = element_blank(),
       y = "Log2 Total Transcript Count",
       title = "Transcript abundance for each assay") +
  scale_y_continuous(limits = c(0, 22), # This sets the min/max on y-axis
                     breaks = seq(0, 30, 5)) +
  scale_fill_manual(values = c("#7777FF", "#FF7777")) +
  facet_wrap(~ CellType, nrow = 3) +
  theme_bw() +
  theme(#legend.position = "none",
        panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
#dev.off()
```

Supp Fig 2G
```{r}
# Pull out negprobe
Tonsil_data_negprobe = Merged_counts_uncorrected %>%
  dplyr::select(Tissue, Region,  CellType, "NegProbe.WTX")

# NegProbe per tissue, mean + sd per celltype
Tonsil_negprobe_mean_celltype = Tonsil_data_negprobe %>%
  mutate(across(where(is.numeric), ~2^.)) %>% # undo log2 first before summing values
  group_by(Tissue, CellType) %>%
  mutate(sum = sum(NegProbe.WTX),
         mean = mean(NegProbe.WTX),
         sd = sd(NegProbe.WTX)) %>%
  distinct(Tissue, CellType, sum, mean, sd)

#pdf('.../SuppFig2G.pdf')
ggplot(Tonsil_negprobe_mean_celltype,
             aes(x = Tissue,
                 y = mean,
                 fill = Tissue)) +
  geom_bar(stat = "identity",
           color = "black") +
  geom_errorbar(aes(x = Tissue,
                    ymin = mean - sd,
                    ymax = mean + sd),
                width = 0.4) + 
  facet_wrap(~ CellType, nrow = 3) +
  labs(title = "Negative Probe Count") +
  scale_fill_manual(values = c("#7777FF", "#FF7777")) +
  theme_bw() +
  theme(#legend.position = "none",
        panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
#dev.off()
```



Fig. 2E
```{r}
### Fig. 2E right
# Load annotation data
L24_annotation = read.csv('.../L24_ROI.csv')
L25_annotation = read.csv('.../L25_ROI.csv')

L24_cellLabel = read.csv('.../L24.csv') %>%
  mutate(ROI = str_replace_all(ROI, "ROI_(\\d+)", function(x) {
    sprintf("%03d", as.numeric(str_extract(x, "\\d+")))}))
L25_cellLabel = read.csv('.../L25.csv') %>%
  mutate(ROI = str_replace_all(ROI, "ROI_(\\d+)", function(x) {
    sprintf("%03d", as.numeric(str_extract(x, "\\d+")))}))

L24_annotation = L24_cellLabel %>%
  left_join(L24_annotation, by = "cellLabel") %>%
  mutate(ROI = paste0(tissue, ".", ROI))
L25_annotation = L25_cellLabel %>%
  left_join(L25_annotation, by = "cellLabel") %>%
  mutate(ROI = paste0(tissue, ".", ROI))

Total_annotation = L24_annotation %>%
  rbind(L25_annotation) %>%
  dplyr::select(ROI, Annotation, tissue) %>%
  dplyr::filter(!str_detect(ROI, "NA"))

# Generate B cell proportion per ROI
Total_annotation_proportion = Total_annotation %>%
  group_by(ROI, Annotation) %>%
  mutate(Count = n()) %>%
  ungroup() %>%
  group_by(ROI) %>%
  mutate(Total_Count = n(),
         Proportion = 100*Count/Total_Count) %>%
  ungroup() %>%
  distinct()

B_proportion = Total_annotation_proportion %>%
  dplyr::filter(str_detect(Annotation, "B Cell")) %>%
  group_by(ROI) %>%
  mutate(ProportionSum = sum(Proportion)) %>%
  arrange(desc(ProportionSum))

# Get T-cell signatures
ROI_analysis_data = Merged_counts %>%
  dplyr::filter(CellType == "CD4T") %>%
  mutate(Tissue = case_when(
    Tissue == "X20240312_Tonsil_L24_ReScan2" ~ "L24",
    Tissue == "X20240312_Tonsil_L25" ~ "L25")) %>%
  mutate(Tissue = paste(Tissue, Region, sep = ".")) %>%
  dplyr::select(-c(Region, CellType)) %>%
  column_to_rownames(var = "Tissue") %>%
  t()

# Use signatures from Immunity paper
Tfh_sig = read_csv('tableSupp1_TonsilSignatures.csv')

# GSVA score
pathways_GSVA_2 = list(Tfh_signatures = Tfh_sig)

GSVA_selection = gsva(ROI_analysis_data,
                      pathways_GSVA_2,
                      method = 'gsva',
                      mx.diff = TRUE)

# Do correlation plot
GSVA_selection_df = GSVA_selection %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "ROI") %>%
  dplyr::select(ROI, "Tfh_signatures") %>%
  left_join(B_proportion, by = "ROI") %>%
  dplyr::select(ROI, "Tfh_signatures", ProportionSum) %>%
  distinct()

#pdf('.../Fig2E_right.pdf')
ggplot(GSVA_selection_df,
       aes(x = `ProportionSum`,
           y = `Tfh_signatures`)) +
  geom_point(size = 1,
             alpha = 1) +
  geom_smooth(method = lm,
              se = TRUE) +
  stat_cor(method = "spearman") +
  labs(y = "Tfh GSVA Score",
       x = "B Cell Proportion per ROI") +
  theme_bw() +
  theme(panel.grid = element_blank())
#dev.off()



### Fig. 2E left
# Binning into high vs low
GSVA_selection_df_bin = GSVA_selection_df %>%
  mutate(Color2 = case_when(ROI %in% c("L24.000", "L25.000",
                           "L24.006", "L25.006",
                           "L24.013", "L25.013") ~ "Low",
                           ROI %in% c("L24.002", "L25.002",
                           "L24.004", "L25.004",
                           "L24.014", "L25.014") ~ "High",
                           TRUE ~ "Med")) %>%
  dplyr::filter(!Color2 %in% "Med") %>%
  group_by(Color2) %>%
  mutate(Mean_Tfh = mean(Tfh_signatures),
         sd_Tfh = sd(Tfh_signatures)) %>%
  ungroup()

#pdf('.../Fig2E_left.pdf')
ggplot(GSVA_selection_df_bin,
             aes(x = fct_inorder(Color2),
                 y = Tfh_signatures,
                 fill = Color2)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1) +
  geom_point(size = 1) +
  labs(x = "Follicle Proportion in ROI",
       y = "Tfh Signatures GSVA score") +
  scale_fill_manual(values = c("#7777FF", "#FF7777")) +
  theme_bw() +
  theme(#legend.position = "none",
        panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  geom_signif(comparisons = list(c("High", "Low")),
             tip_length = 0,
             test = "wilcox.test",
             map_signif_level = FALSE,
             y_position = c(0.34))
#dev.off()
```



Fig 2F
```{r}
### prepare data for cNMF; one row is one "cell"
cNMF_df = Merged_counts %>%
  dplyr::filter(Region != "Control") %>%
  mutate(Tissue = case_when(
    Tissue == "X20240312_Tonsil_L24_ReScan2" ~ "L24",
    Tissue == "X20240312_Tonsil_L25" ~ "L25")) %>%
  mutate(Tissue = paste(Tissue, Region, CellType, sep = "_")) %>%
  dplyr::select(-c(Region, CellType)) %>%
  column_to_rownames(var = "Tissue")

write.csv(cNMF_df,
          file = '.../tonsil_count.csv',
          row.names = F)

# Find number of highly variable genes using Seurat
cNMF_df_seuratObjMatrix = cNMF_df %>%
  t()

cNMF_df_seuratObj = CreateSeuratObject(counts = cNMF_df_seuratObjMatrix,
                                       names.delim = "-",
                                       names.field = 1)

cNMF_df_seuratObj = SetAssayData(object = Merged_counts_seuratObj,
                                 slot = "data",
                                 new.data = Merged_counts_seuratObjMatrix)

cNMF_df_hvg_seurat = FindVariableFeatures(cNMF_df_seuratObj,
                                          selection.method = "vst",
                                          nfeatures = ncol(cNMF_df))

cNMF_df_hvg = cNMF_df_hvg_seurat@assays$RNA@meta.data %>%
  dplyr::select(vf_vst_counts_variance.standardized, var.features, var.features.rank)

# kmeans cutoff for number of HVG
set.seed(1)

cNMF_df_hvg_kmeans = kmeans(cNMF_df_hvg %>%
                              dplyr::select(vf_vst_counts_variance.standardized) %>%
                              as.matrix(),
                            centers = 9)

cNMF_df_hvg = cNMF_df_hvg %>%
  mutate(cluster = cNMF_df_hvg_kmeans$cluster)

cNMF_df_hvg_cluster = cNMF_df_hvg %>%
  group_by(cluster) %>%
  dplyr::filter(vf_vst_counts_variance.standardized == min(vf_vst_counts_variance.standardized)) %>%
  ungroup()

# Visualization
ggplot(cNMF_df_hvg,
  aes(x = var.features.rank,
      y = vf_vst_counts_variance.standardized)) +
  geom_point(size = 0.5) +
  theme_bw() +
  geom_vline(data = cNMF_df_hvg_cluster,
             aes(xintercept = var.features.rank,
                 color = as.factor(var.features.rank)),
             linetype = "dashed",
             linewidth = 0.5)

ERROR_ON_PURPOSE

### Return only when cNMF is done
k = 26 # indicate number of GEPs

# Load usage scores
cNMF_usage = read.csv('.../tonsil_cnmf26_usage.csv', row.names = 1)
cNMF_topg = read.csv('.../tonsil_top100_genes_cnmf26.csv')

cNMF_usage = cNMF_usage %>%
  rename_all(~ str_replace_all(., 'Usage', 'Program')) # quick rename
colnames(cNMF_topg) = colnames(cNMF_usage)

# Get GEP for each cell type
cNMF_usage_celltype = cNMF_usage %>%
  mutate(tissueid = rownames(cNMF_df)) %>%
  separate(tissueid,
           into = c("tissue", "region", "celltype"),
           sep = "_") %>%
  dplyr::select(-c("tissue", "region")) %>%
  group_by(celltype) %>%
  summarize(across(where(is.numeric), mean), .groups = "drop") %>%
  column_to_rownames(var = "celltype")

### enrichR scoring and GEP annotation
dbs = c("GO_Biological_Process_2015")

program_names = colnames(cNMF_topg)
program_GOBP_all = tibble()

# Loop through each program
for (program in program_names) {
  program_check_numGenes = 50
  
  program_genes = cNMF_topg %>%
    pull(program) %>%
    .[1:program_check_numGenes]
  
  enriched = enrichr(genes = program_genes, dbs)
  
  program_GOBP = enriched$GO_Biological_Process_2015 %>%
    dplyr::slice(1:10) %>%
    mutate(Program = program)

  program_GOBP_all = rbind(program_GOBP_all, program_GOBP) %>%
    dplyr::select(Program, everything())
}

write.csv(program_GOBP_all,
          file = '.../cNMF_GOBP.csv',
          row.names = F)

### main figure heatmap output
#pdf(file = ".../Fig2F.pdf")
Heatmap(cNMF_usage_celltype %>% scale(),
        name = "Z score",
        col = colorRamp2(c(-2, 0, 2),
                         c("#FF00FF", "#000000", "#FFFF00")),
        show_column_names = TRUE,
        column_order = sort(colnames(cNMF_usage_celltype)),
        row_order = sort(rownames(cNMF_usage_celltype)),
        border = "black",
        column_names_gp = gpar(fontsize = 8),
        row_names_gp = gpar(fontsize = 8))
#dev.off()
```